//
// Created by Achmad Fatoni on 11/3/15.
// Copyright (c) 2015 Achmad Fatoni. All rights reserved.
//

//print("test country")
//self.tiketApi.listCountry { (countries) -> Void in
//    var countryIdArr = [String]();
//    var countryNameDict = [String:String]()
//    
//    
//    for country in countries["listCountry"].array! {
//        var countryId = country["country_id"].string!
//        
//        countryIdArr.append(countryId)
//        
//        countryNameDict[countryId] = country["country_name"].string!
//    }
//    
//    print("---------- country Id array----------")
//    print(countryIdArr)
//    
//    print("---------- country Id dict----------")
//    print(countryNameDict)
//}


import Foundation

class Countries {

    var countryIdArray = [
            "id","af", "ax", "al", "dz", "as", "ad", "ao", "ai", "aq", "ag",
            "ar", "am", "aw", "au", "at", "az", "bs", "bh", "bd", "bb",
            "by", "be", "bz", "bj", "bm", "bt", "bo", "ba", "bw", "bv",
            "br", "io", "bn", "bg", "bf", "bi", "kh", "cm", "ca", "cv",
            "ky", "cf", "td", "cl", "cn", "cx", "cc", "co", "km", "cg",
            "cd", "ck", "cr", "ci", "hr", "cu", "cy", "cz", "dk", "dj",
            "dm", "do", "ec", "eg", "sv", "gq", "er", "ee", "et", "fk",
            "fo", "fj", "fi", "fr", "gf", "pf", "tf", "ga", "gm", "ge",
            "de", "gh", "gi", "gr", "gl", "gd", "gp", "gu", "gt", "gg",
            "gn", "gw", "gy", "ht", "hm", "hn", "hk", "hu", "is", "in",
            "ir", "iq", "ie", "im", "il", "it", "jm", "jp", "je",
            "jo", "kz", "ke", "ki", "kw", "kg", "la", "lv", "lb", "ls",
            "lr", "ly", "li", "lt", "lu", "mo", "mk", "mg", "mw", "my",
            "mv", "ml", "mt", "mh", "mq", "mr", "mu", "yt", "mx", "fm",
            "md", "mc", "mn", "me", "ms", "ma", "mz", "mm", "na", "nr",
            "np", "nl", "an", "nc", "nz", "ni", "ne", "ng", "nu", "nf",
            "kp", "mp", "no", "om", "pk", "pw", "ps", "pa", "pg", "py",
            "pe", "ph", "pn", "pl", "pt", "pr", "qa", "re", "ro", "ru",
            "rw", "bl", "sh", "kn", "lc", "mf", "pm", "vc", "ws", "sm",
            "st", "sa", "sn", "rs", "sc", "sl", "sg", "sk", "si", "sb",
            "so", "za", "gs", "kr", "es", "lk", "sd", "sr", "sj", "sz",
            "se", "ch", "sy", "tw", "tj", "tz", "th", "tl", "tg", "tk",
            "to", "tt", "tn", "tr", "tm", "tc", "tv", "ug", "ua", "ae",
            "gb", "us", "um", "uy", "uz", "vu", "va", "ve", "vn", "vg",
            "vi", "wf", "eh", "ye", "zm", "zw"
    ]
    var countryNameArray = [
            "er": "Eritrea ",
            "iq": "Iraq ",
            "gr": "Greece ",
            "mg": "Madagascar ",
            "sb": "Solomon Islands ",
            "va": "Vatican City State ",
            "lc": "Saint Lucia ",
            "bn": "Brunei Darussalam ",
            "il": "Israel ",
            "st": "Sao Tome And Principe ",
            "tc": "Turks And Caicos Islands ",
            "sk": "Slovakia ",
            "ao": "Angola ",
            "gg": "Guernsey ",
            "aq": "Antarctica ",
            "ad": "Andorra ",
            "za": "South Africa ",
            "bh": "Bahrain ",
            "io": "British Indian Ocean Territory ",
            "ax": "land Islands ",
            "mx": "Mexico ",
            "sg": "Singapore ",
            "nc": "New Caledonia ",
            "tg": "Togo ",
            "jo": "Jordan ",
            "mh": "Marshall Islands ",
            "np": "Nepal ", "nz": "New Zealand ",
            "an": "Netherlands Antilles ",
            "py": "Paraguay ",
            "ps": "Palestinian Territory Occupied ",
            "ne": "Niger ", "bd": "Bangladesh ",
            "pf": "French Polynesia ",
            "ng": "Nigeria ",
            "et": "Ethiopia ",
            "tf": "French Southern Territories ",
            "cy": "Cyprus ",
            "pg": "Papua New Guinea ",
            "ms": "Montserrat ",
            "bm": "Bermuda ",
            "mq": "Martinique ",
            "bo": "Bolivia ",
            "cv": "Cape Verde ",
            "fi": "Finland ",
            "cf": "Central African Republic ",
            "sl": "Sierra Leone ",
            "tt": "Trinidad And Tobago ",
            "kz": "Kazakhstan ",
            "mp": "Northern Mariana Islands ",
            "ai": "Anguilla ", "km": "Comoros ",
            "in": "India ",
            "lk": "Sri Lanka ",
            "sd": "Sudan ",
            "az": "Azerbaijan ",
            "au": "Australia ",
            "pe": "Peru ",
            "bl": "Saint Barthlemy ",
            "ma": "Morocco ",
            "ch": "Switzerland ",
            "de": "Germany ",
            "to": "Tonga ",
            "ky": "Cayman Islands ",
            "td": "Chad ",
            "bb": "Barbados ",
            "sz": "Swaziland ",
            "tw": "Taiwan",
            "pw": "Palau ",
            "pr": "Puerto Rico ",
            "ml": "Mali ",
            "li": "Liechtenstein ",
            "lu": "Luxembourg ",
            "vc": "Saint Vincent And The Grenadines ",
            "yt": "Mayotte ", "vi": "Virgin Islands US ",
            "it": "Italy ",
            "gf": "French Guiana ",
            "so": "Somalia ",
            "lr": "Liberia ", "mw": "Malawi ",
            "hr": "Croatia ",
            "vn": "Vietnam ",
            "ls": "Lesotho ",
            "sj": "Svalbard And Jan Mayen ",
            "al": "Albania ",
            "tv": "Tuvalu ",
            "gt": "Guatemala ",
            "us": "United States ",
            "fj": "Fiji ",
            "ph": "Philippines ",
            "jm": "Jamaica ",
            "sr": "Suriname ",
            "ve": "Venezuela ",
            "gm": "Gambia ",
            "gi": "Gibraltar ",
            "am": "Armenia ",
            "dk": "Denmark ",
            "br": "Brazil ",
            "lb": "Lebanon ",
            "ru": "Russia",
            "kg": "Kyrgyzstan ",
            "mr": "Mauritania ",
            "mf": "Saint Martin ",
            "eg": "Egypt",
            "sv": "El Salvador ",
            "bt": "Bhutan ",
            "dm": "Dominica ",
            "mk": "Macedonia The Former Yugoslav Republic Of ",
            "cl": "Chile ", "vg": "Virgin Islands British ",
            "rw": "Rwanda ", "by": "Belarus ", "ie": "Ireland ",
            "om": "Oman ",
            "tn": "Tunisia ",
            "ba": "Bosnia And Herzegovina ",
            "gh": "Ghana ", "cr": "Costa Rica ",
            "fr": "France ",
            "se": "Sweden ",
            "mv": "Maldives ",
            "gp": "Guadeloupe ",
            "aw": "Aruba ",
            "cx": "Christmas Island ",
            "tk": "Tokelau ",
            "fo": "Faroe Islands ",
            "ua": "Ukraine ",
            "pl": "Poland ",
            "mo": "Macau ",
            "ro": "Romania ",
            "tl": "TimorLeste ",
            "na": "Namibia ",
            "id": "Indonesia",
            "la": "Laos",
            "nr": "Nauru ",
            "rs": "Serbia ",
            "ae": "United Arab Emirates ",
            "ug": "Uganda ",
            "cu": "Cuba ",
            "uy": "Uruguay ",
            "si": "Slovenia ",
            "pt": "Portugal ",
            "gs": "South Georgia And The South Sandwich Islands ",
            "um": "United States Minor Outlying Islands ",
            "zm": "Zambia ",
            "bg": "Bulgaria ",
            "gd": "Grenada ",
            "me": "Montenegro ",
            "pa": "Panama ",
            "sy": "Syrian Arab Republic ",
            "mc": "Monaco ",
            "gw": "GuineaBissau ",
            "ly": "Libyan Arab Jamahiriya ",
            "vu": "Vanuatu ",
            "cm": "Cameroon ",
            "je": "Jersey ",
            "mu": "Mauritius ",
            "re": "Runion ",
            "gb": "United Kingdom ",
            "cc": "Cocos Keeling Islands ",
            "bs": "Bahamas ",
            "sa": "Saudi Arabia ",
            "is": "Iceland ",
            "kr": "South Korea",
            "at": "Austria ",
            "fk": "Falkland Islands Malvinas ",
            "bi": "Burundi ",
            "cz": "Czech Republic ",
            "bj": "Benin ",
            "ci": "Cte DIvoire ",
            "ee": "Estonia ",
            "ke": "Kenya ",
            "kh": "Cambodia ",
            "kp": "North Korea",
            "pk": "Pakistan ",
            "pn": "Pitcairn ",
            "es": "Spain ",
            "hn": "Honduras ",
            "ws": "Samoa ",
            "kn": "Saint Kitts And Nevis ",
            "sc": "Seychelles ",
            "tr": "Turkey ",
            "gn": "Guinea ",
            "md": "Moldova ",
            "no": "Norway ",
            "bv": "Bouvet Island ",
            "tj": "Tajikistan ",
            "uz": "Uzbekistan ",
            "gy": "Guyana ",
            "lt": "Lithuania ",
            "nf": "Norfolk Island ",
            "sm": "San Marino ",
            "do": "Dominican Republic ",
            "be": "Belgium ",
            "mn": "Mongolia ",
            "mz": "Mozambique ",
            "ki": "Kiribati ",
            "cd": "Congo The Democratic Republic Of The ",
            "ec": "Ecuador ",
            "gu": "Guam ",
            "tz": "Tanzania",
            "gl": "Greenland ",
            "mt": "Malta ",
            "mm": "Myanmar ",
            "cn": "China ",
            "as": "American Samoa ",
            "lv": "Latvia ",
            "hk": "Hong Kong ",
            "tm": "Turkmenistan ",
            "bz": "Belize ",
            "ge": "Georgia ",
            "ht": "Haiti ",
            "wf": "Wallis And Futuna ",
            "nu": "Niue ",
            "hm": "Heard Island And Mcdonald Islands ",
            "pm": "Saint Pierre And Miquelon ",
            "ca": "Canada ",
            "ag": "Antigua And Barbuda ",
            "bf": "Burkina Faso ",
            "my": "Malaysia ",
            "qa": "Qatar ",
            "eh": "Western Sahara ",
            "ir": "Iran Islamic Republic Of ",
            "af": "Afghanistan ", "hu": "Hungary ",
            "co": "Colombia ",
            "sh": "Saint Helena ",
            "ga": "Gabon ",
            "bw": "Botswana ",
            "sn": "Senegal ",
            "th": "Thailand ",
            "zw": "Zimbabwe",
            "ye": "Yemen ",
            "jp": "Japan ",
            "cg": "Congo ",
            "fm": "Micronesia Federated States Of ",
            "dz": "Algeria ",
            "im": "Isle Of Man ",
            "nl": "Netherlands ",
            "ni": "Nicaragua ",
            "dj": "Djibouti ",
            "ar": "Argentina ",
            "gq": "Equatorial Guinea ",
            "ck": "Cook Islands ",
            "kw": "Kuwait "
    ]
}